### ISSUE TITLE
Love the mod... but

### ISSUE THREAD

**Issue by Elkinsrg** [Zarathul/simplefluidtanks#7] opened 2015-02-22 21:52 UTC
I have a bug to report and a few ideas that you may or may not have heard before. 

My bug is that when I place a valve ANYWHERE but the bottom most tank blocks it crashes. 

My Ideas are, a Drain Block that can remove liquid from a tank and there can be as many as will fit. The bonus is that you can remove it without destroying your tank which makes it a lot less painful when you have the neather's worth of lava in a tank and want to move the valve. 

Some kind of screen or display that shows how much you have in the tank. Something as simple as 30 Buckets of Iron or 300 Ingots or something. 

An Upgraded Valve/Drain That pumps liquid into builcraft pipes with the application of a redstone signal. The recipe could be a valve/drain and a restone engine or something. 

Oh, and lastly, this just makes sense. If I have a tank full of lava, I'd love to see it actually light up the area around it. 

I'm playing 1.7.10 and the most recent version of your mod. Perhaps you have fixed these problems or implimented some of the ideas I've had. Either way, I love this mod; It's the best tank mod I've ever seen.

Thank you for your time.
Elkinsrg

**Comment by Zarathul** [comment] 2015-02-23 13:54
> My bug is that when I place a valve ANYWHERE but the bottom most tank blocks it crashes. 

I can't reproduce that. The crashlog and a screenshot would help.

> My Ideas are, a Drain Block that can remove liquid from a tank and there can be as many as will fit.

I might look at that after porting to 1.8.

> Some kind of screen or display..

Doesn't fit the theme of the tanks (low-tech). Also you can already build a fill status indicator using a comparator.

> An Upgraded Valve/Drain That pumps liquid into builcraft pipes ...

I don't see a need for that. Usually pipes do the pumping.

> Oh, and lastly, this just makes sense. If I have a tank full of lava, I'd love to see it actually light up the area around it.

I already experimented with that and unfortunately it was a performance nightmare, especially with larger tanks. I might look at this again in the future.

**Comment by Zarathul** [comment] 2015-03-07 17:10
No reply in almost 2 weeks, so I'm closing this. If the issue persists and your able to provide a crashlog, feel free to open a new ticket.

**Closed as completed by Zarathul** 2015-03-07 17:10 UTC
Labels: enhancement, clarification needed

**Comment by Elkinsrg** [comment] 2015-03-07 17:31
Sorry, I expected this site to email me when I got your reply. I will give you a crash log next time it happens.

**Comment by Elkinsrg** [comment] 2015-03-07 17:32
Oh, btw, do you have a link on how to make a level indicator out of a comparator?

**Comment by Zarathul** [comment] 2015-03-08 15:19
> Oh, btw, do you have a link on how to make a level indicator out of a comparator?

https://www.youtube.com/watch?v=uR9GqDqolVs&t=465
